### PR TITLE
chore. Update module and fix bugs in build

### PR DESCRIPTION
**Pull request by jorge990125**
## Changes Proposed:
-  Update sql and npcpromotion.cpp
-  Change the `getLevel` method to `GetLevel`
- Update the method of writing commands

## Tests Performed:

- build without problems
- Windows 10

## How to Test the Changes:

1. update module
2. generate project with cmake
3. compile the project again

### CODE REVIEW

**Comment by pangolp** [comment]
Thank you. I'm running the tests. If all goes well, we merged it.

**Comment by pangolp** [comment]
Do you want to correct the errors yourself or do you want me to correct them? I'll be waiting for anything.

**Comment by jorge990125** [comment]
> ¿Quieres corregir los errores tú mismo o prefieres que los corrija yo? Estaré atento a cualquier cosa.

If you can correct them I would appreciate it, if not, when I come home from work I will correct the errors.

**Comment by pangolp** [comment]
> > ¿Quieres corregir los errores tú mismo o prefieres que los corrija yo? Estaré atento a cualquier cosa.
> 
> If you can correct them I would appreciate it, if not, when I come home from work I will correct the errors.

The case was useful to me, to show how a person can contribute to another person's branch, even if that person did not create the pull request. But there is no rush, and other scenarios may arise in the future. That's why I asked you, to know if I should get involved or not.

**Comment by pangolp** [comment]
I left you some suggestions, none of them are really obligatory, they are more than anything recommendations, to respect the way of writing things, but none of them play a really important role in this case.

**Comment by jorge990125** [comment]
> I left you some suggestions, none of them are really obligatory, they are more than anything recommendations, to respect the way of writing things, but none of them play a really important role in this case.

I really like it when you give me advice since I don't know everything and every day you learn something new, learning from mistakes is wise, so any help I receive will always be appreciated.

**Comment by pangolp** [comment]
Don't worry about the number of commits that are formed within this pull request, because when the merge is performed, using the Squash and merge option, all the commits are combined into just 1, regardless of the number that have been generated within this branch.

**Comment by pangolp** [comment]
The tests passed without any problems. However, the changes I mentioned above would have to be made. I can do them myself, or if you want and have time, if you want to do them yourself, no problem. Let me know. I'll be waiting.

**Comment by jorge990125** [comment]
Ok, if you can do it, I would appreciate it very much.

**Comment by pangolp** [comment]
> Ok, if you can do it, I would appreciate it very much.

Perfect, I'll do it.

**Comment by pangolp** [comment]
On GitHub, by default, there is an option configured to accept commits from other people on some branches. You have to check if you have that option enabled, because I think not. I don't remember if it can be enabled within each pull request, or if it is an account setting.

image

image

image

**Comment by jorge990125** [comment]
I already activated the option

**Comment by pangolp** [comment]
> I already activated the option

Perfect, I can now commit. Now we need to wait for the tests to pass, and check if there is anything else pending. I have to test in-game if it works, because I haven't tested it and since we made changes to the command, we will have to test that part.

**Comment by pangolp** [comment]
Apparently, there is a small failure, when using the command. But now I correct it. The rest, it seems that everything is fine.

```
[09:12:54]  ------------------------------------------------     
[09:12:54]  Username : ADMIN
[09:12:54]  Email : 
[09:12:54]  Last IP : 127.0.0.1
[09:12:54]  Online :  [ONLINE]
[09:12:54]  Recruiter : 25862
[09:12:54]  ------------------------------------------------     
[09:12:54]       --- LISTA DE PERSONAJES ---                     
[09:12:54] Wrong format occurred (argument not found). Fmt string: 'Character: {}, {}: {}, date: {}'
```

**Comment by pangolp** [comment]
Done, it is now fixed, if it passes the tests, we merge it.

```
[09:19:20]  ------------------------------------------------     
[09:19:20]  Username : ADMIN
[09:19:20]  Email : 
[09:19:20]  Last IP : 127.0.0.1
[09:19:20]  Online :  [ONLINE]
[09:19:20]  Recruiter : 26271
[09:19:20]  ------------------------------------------------     
[09:19:20]       --- LISTA DE PERSONAJES ---                     
[09:19:20] Character: Stevej - IP: 127.0.0.1 - date: 2024-08-31 09:07:56
```

**Review by pangolp — APPROVED** [review]

**Comment by pangolp** [comment]
Merged. Thanks.

**Pull request merged**
